
#ifndef NCUERPOSPROJECTSECUENCIAL_LIB_COORDENADAS_H_
#define NCUERPOSPROJECTSECUENCIAL_LIB_COORDENADAS_H_


	typedef struct
	{
		int x;
		int y;
	}TCoordenada;


#endif /* NCUERPOSPROJECTSECUENCIAL_LIB_COORDENADAS_H_ */
