
#ifndef NCUERPOSPROJECTOPENMP_LIB_COORDENADAS_H_
#define NCUERPOSPROJECTOPENMP_LIB_COORDENADAS_H_


	typedef struct
	{
		int x;
		int y;
	}TCoordenada;


#endif /* NCUERPOSPROJECTOPENMP_LIB_COORDENADAS_H_ */
