
#ifndef NCUERPOSPROJECTSECUENCIAL_LIB_FICHERO_H_
#define NCUERPOSPROJECTSECUENCIAL_LIB_FICHERO_H_


#include <stdio.h>



void guardar_en_fichero(FILE*, char*);



#endif /* NCUERPOSPROJECTSECUENCIAL_LIB_FICHERO_H_ */
